[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[profile.pos]
fork_block_number = 42054744
eth-rpc-url = "https://polygon-rpc.com"
etherscan-api-key = ""

[profile.zkevm]
eth-rpc-url = "https://zkevm-rpc.com/"
etherscan-api-key = ""

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
